version: "3.9"

name: "dental-crm"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dental-crm-backend
    ports:
      - "5000:3000"
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: mydb
      NODE_ENV: development
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dental-crm-frontend
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: development
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

  mysql:
    image: mysql:8.0
    container_name: dental-crm-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
