import { MigrationInterface, QueryRunner } from "typeorm";

export class AddTimestampsToUsers1743705213140 implements MigrationInterface {
    name = 'AddTimestampsToUsers1743705213140'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_8ff6d2f32e511dfb73c832c961b\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_c07863a38c0ca837decb81b28ac\``);
        await queryRunner.query(`ALTER TABLE \`appointments\` DROP FOREIGN KEY \`FK_669db51cd07b8a65bee9aaf9c4a\``);
        await queryRunner.query(`ALTER TABLE \`appointments\` DROP FOREIGN KEY \`FK_a653f25083f24810a2988e9d125\``);
        await queryRunner.query(`ALTER TABLE \`patient_treatments\` DROP FOREIGN KEY \`FK_2593abd5b1546954e5fd64de544\``);
        await queryRunner.query(`ALTER TABLE \`patient_treatments\` DROP FOREIGN KEY \`FK_81ab01dc3f9a00a10eb08b4d091\``);
        await queryRunner.query(`ALTER TABLE \`patient_treatments\` DROP FOREIGN KEY \`FK_9b7ee5bc21373d8458d61d5b854\``);
        await queryRunner.query(`ALTER TABLE \`billing\` DROP FOREIGN KEY \`FK_7a4cbee232167f589034579058d\``);
        await queryRunner.query(`ALTER TABLE \`billing\` DROP FOREIGN KEY \`FK_f22ac204d60b28abdbe5d846570\``);
        await queryRunner.query(`DROP INDEX \`IDX_902985a964245652d5e3a0f5f6\` ON \`staff\``);
        await queryRunner.query(`DROP INDEX \`IDX_64e2031265399f5690b0beba6a\` ON \`patients\``);
        await queryRunner.query(`DROP INDEX \`REL_c07863a38c0ca837decb81b28a\` ON \`users\``);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP COLUMN \`email\``);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP COLUMN \`role\``);
        await queryRunner.query(`ALTER TABLE \`staff\` CHANGE \`staff_id\` \`staff_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP COLUMN \`staff_id\``);
        await queryRunner.query(`ALTER TABLE \`patients\` DROP COLUMN \`email\``);
        await queryRunner.query(`ALTER TABLE \`patients\` CHANGE \`patient_id\` \`patient_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`patients\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`patients\` DROP COLUMN \`patient_id\``);
        await queryRunner.query(`ALTER TABLE \`patients\` DROP COLUMN \`registration_date\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`patientPatientId\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`staffStaffId\``);
        await queryRunner.query(`ALTER TABLE \`treatments\` CHANGE \`treatment_id\` \`treatment_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`treatments\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`treatments\` DROP COLUMN \`treatment_id\``);
        await queryRunner.query(`ALTER TABLE \`appointments\` CHANGE \`appointment_id\` \`appointment_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`appointments\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`appointments\` DROP COLUMN \`appointment_id\``);
        await queryRunner.query(`ALTER TABLE \`appointments\` DROP COLUMN \`notes\``);
        await queryRunner.query(`ALTER TABLE \`appointments\` DROP COLUMN \`patientPatientId\``);
        await queryRunner.query(`ALTER TABLE \`appointments\` DROP COLUMN \`staffStaffId\``);
        await queryRunner.query(`ALTER TABLE \`patient_treatments\` DROP COLUMN \`appointmentAppointmentId\``);
        await queryRunner.query(`ALTER TABLE \`patient_treatments\` CHANGE \`patient_treatment_id\` \`patient_treatment_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`patient_treatments\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`patient_treatments\` DROP COLUMN \`patient_treatment_id\``);
        await queryRunner.query(`ALTER TABLE \`patient_treatments\` DROP COLUMN \`patientPatientId\``);
        await queryRunner.query(`ALTER TABLE \`patient_treatments\` DROP COLUMN \`treatmentTreatmentId\``);
        await queryRunner.query(`ALTER TABLE \`billing\` DROP COLUMN \`amount_paid\``);
        await queryRunner.query(`ALTER TABLE \`billing\` DROP COLUMN \`appointmentAppointmentId\``);
        await queryRunner.query(`ALTER TABLE \`billing\` CHANGE \`bill_id\` \`bill_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`billing\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`billing\` DROP COLUMN \`bill_id\``);
        await queryRunner.query(`ALTER TABLE \`billing\` DROP COLUMN \`patientPatientId\``);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD \`id\` int NOT NULL PRIMARY KEY AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD \`user_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD UNIQUE INDEX \`IDX_cec9365d9fc3a3409158b645f2\` (\`user_id\`)`);
        await queryRunner.query(`ALTER TABLE \`patients\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`patients\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`patients\` ADD \`id\` int NOT NULL PRIMARY KEY AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`patients\` ADD \`user_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`patients\` ADD UNIQUE INDEX \`IDX_7fe1518dc780fd777669b5cb7a\` (\`user_id\`)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`treatments\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`treatments\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`treatments\` ADD \`id\` int NOT NULL PRIMARY KEY AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`treatments\` ADD \`cost_comment\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`appointments\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`appointments\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`appointments\` ADD \`id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`appointments\` ADD \`patientId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`appointments\` ADD \`staffId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`patient_treatments\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`patient_treatments\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`patient_treatments\` ADD \`id\` int NOT NULL PRIMARY KEY AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`patient_treatments\` ADD \`treatment\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`patient_treatments\` ADD \`patientId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`patient_treatments\` ADD \`appointmentId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`billing\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`billing\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`billing\` ADD \`id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`billing\` ADD \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`billing\` ADD \`appointmentId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`staff\` CHANGE \`gender\` \`gender\` enum ('male', 'female', 'other') NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD UNIQUE INDEX \`IDX_7b250e1934a3375a7db2668655\` (\`contact_number\`)`);
        await queryRunner.query(`ALTER TABLE \`patients\` CHANGE \`gender\` \`gender\` enum ('male', 'female', 'other') NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`patients\` ADD UNIQUE INDEX \`IDX_e057c0946cc7e3f7bc98046dee\` (\`contact_number\`)`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`role\` \`role\` enum ('admin', 'receptionist', 'dentist', 'patient', 'guest') NOT NULL DEFAULT 'guest'`);
        await queryRunner.query(`ALTER TABLE \`treatments\` ADD UNIQUE INDEX \`IDX_3f796d4d1446b284c0fc10e5d0\` (\`treatment_name\`)`);
        await queryRunner.query(`ALTER TABLE \`appointments\` CHANGE \`status\` \`status\` enum ('scheduled', 'completed', 'cancelled', 'no-show') NOT NULL DEFAULT 'scheduled'`);
        await queryRunner.query(`ALTER TABLE \`billing\` CHANGE \`payment_status\` \`payment_status\` enum ('paid', 'pending') NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_cec9365d9fc3a3409158b645f2\` ON \`staff\` (\`user_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_7fe1518dc780fd777669b5cb7a\` ON \`patients\` (\`user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_b5847286e39c93ccc26614c047\` ON \`billing\` (\`id\`, \`appointmentId\`)`);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD CONSTRAINT \`FK_cec9365d9fc3a3409158b645f2e\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`patients\` ADD CONSTRAINT \`FK_7fe1518dc780fd777669b5cb7a0\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`appointments\` ADD CONSTRAINT \`FK_13c2e57cb81b44f062ba24df57d\` FOREIGN KEY (\`patientId\`) REFERENCES \`patients\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`appointments\` ADD CONSTRAINT \`FK_47d806acd1838f94d3c42bb4d49\` FOREIGN KEY (\`staffId\`) REFERENCES \`staff\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`patient_treatments\` ADD CONSTRAINT \`FK_9e2d6e37d9a24bdb410609e5c46\` FOREIGN KEY (\`patientId\`) REFERENCES \`patients\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`patient_treatments\` ADD CONSTRAINT \`FK_23a2f06f8131bd521802e5d1a0e\` FOREIGN KEY (\`appointmentId\`) REFERENCES \`appointments\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`billing\` ADD CONSTRAINT \`FK_36d7bd0469f81083fa396e5d0df\` FOREIGN KEY (\`appointmentId\`) REFERENCES \`appointments\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`billing\` DROP FOREIGN KEY \`FK_36d7bd0469f81083fa396e5d0df\``);
        await queryRunner.query(`ALTER TABLE \`patient_treatments\` DROP FOREIGN KEY \`FK_23a2f06f8131bd521802e5d1a0e\``);
        await queryRunner.query(`ALTER TABLE \`patient_treatments\` DROP FOREIGN KEY \`FK_9e2d6e37d9a24bdb410609e5c46\``);
        await queryRunner.query(`ALTER TABLE \`appointments\` DROP FOREIGN KEY \`FK_47d806acd1838f94d3c42bb4d49\``);
        await queryRunner.query(`ALTER TABLE \`appointments\` DROP FOREIGN KEY \`FK_13c2e57cb81b44f062ba24df57d\``);
        await queryRunner.query(`ALTER TABLE \`patients\` DROP FOREIGN KEY \`FK_7fe1518dc780fd777669b5cb7a0\``);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP FOREIGN KEY \`FK_cec9365d9fc3a3409158b645f2e\``);
        await queryRunner.query(`DROP INDEX \`IDX_b5847286e39c93ccc26614c047\` ON \`billing\``);
        await queryRunner.query(`DROP INDEX \`REL_7fe1518dc780fd777669b5cb7a\` ON \`patients\``);
        await queryRunner.query(`DROP INDEX \`REL_cec9365d9fc3a3409158b645f2\` ON \`staff\``);
        await queryRunner.query(`ALTER TABLE \`billing\` CHANGE \`payment_status\` \`payment_status\` enum ('Paid', 'Pending', 'Partially Paid') NOT NULL DEFAULT 'Pending'`);
        await queryRunner.query(`ALTER TABLE \`appointments\` CHANGE \`status\` \`status\` enum ('Scheduled', 'Completed', 'Cancelled', 'No-Show') NOT NULL DEFAULT 'Scheduled'`);
        await queryRunner.query(`ALTER TABLE \`treatments\` DROP INDEX \`IDX_3f796d4d1446b284c0fc10e5d0\``);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`role\` \`role\` enum ('Admin', 'Staff', 'Receptionist', 'Dentist', 'Patient', 'Guest') NOT NULL DEFAULT 'Guest'`);
        await queryRunner.query(`ALTER TABLE \`patients\` DROP INDEX \`IDX_e057c0946cc7e3f7bc98046dee\``);
        await queryRunner.query(`ALTER TABLE \`patients\` CHANGE \`gender\` \`gender\` enum ('Male', 'Female', 'Other') NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP INDEX \`IDX_7b250e1934a3375a7db2668655\``);
        await queryRunner.query(`ALTER TABLE \`staff\` CHANGE \`gender\` \`gender\` enum ('Male', 'Female', 'Other') NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`billing\` DROP COLUMN \`appointmentId\``);
        await queryRunner.query(`ALTER TABLE \`billing\` DROP COLUMN \`description\``);
        await queryRunner.query(`ALTER TABLE \`billing\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`billing\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`billing\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`patient_treatments\` DROP COLUMN \`appointmentId\``);
        await queryRunner.query(`ALTER TABLE \`patient_treatments\` DROP COLUMN \`patientId\``);
        await queryRunner.query(`ALTER TABLE \`patient_treatments\` DROP COLUMN \`treatment\``);
        await queryRunner.query(`ALTER TABLE \`patient_treatments\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`patient_treatments\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`patient_treatments\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`appointments\` DROP COLUMN \`staffId\``);
        await queryRunner.query(`ALTER TABLE \`appointments\` DROP COLUMN \`patientId\``);
        await queryRunner.query(`ALTER TABLE \`appointments\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`appointments\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`appointments\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`treatments\` DROP COLUMN \`cost_comment\``);
        await queryRunner.query(`ALTER TABLE \`treatments\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`treatments\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`treatments\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`patients\` DROP INDEX \`IDX_7fe1518dc780fd777669b5cb7a\``);
        await queryRunner.query(`ALTER TABLE \`patients\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`patients\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`patients\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`patients\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP INDEX \`IDX_cec9365d9fc3a3409158b645f2\``);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`billing\` ADD \`patientPatientId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`billing\` ADD \`bill_id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`billing\` ADD PRIMARY KEY (\`bill_id\`)`);
        await queryRunner.query(`ALTER TABLE \`billing\` CHANGE \`bill_id\` \`bill_id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`billing\` ADD \`appointmentAppointmentId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`billing\` ADD \`amount_paid\` decimal NOT NULL DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`patient_treatments\` ADD \`treatmentTreatmentId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`patient_treatments\` ADD \`patientPatientId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`patient_treatments\` ADD \`patient_treatment_id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`patient_treatments\` ADD PRIMARY KEY (\`patient_treatment_id\`)`);
        await queryRunner.query(`ALTER TABLE \`patient_treatments\` CHANGE \`patient_treatment_id\` \`patient_treatment_id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`patient_treatments\` ADD \`appointmentAppointmentId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`appointments\` ADD \`staffStaffId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`appointments\` ADD \`patientPatientId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`appointments\` ADD \`notes\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`appointments\` ADD \`appointment_id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`appointments\` ADD PRIMARY KEY (\`appointment_id\`)`);
        await queryRunner.query(`ALTER TABLE \`appointments\` CHANGE \`appointment_id\` \`appointment_id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`treatments\` ADD \`treatment_id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`treatments\` ADD PRIMARY KEY (\`treatment_id\`)`);
        await queryRunner.query(`ALTER TABLE \`treatments\` CHANGE \`treatment_id\` \`treatment_id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`staffStaffId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`patientPatientId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`patients\` ADD \`registration_date\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`patients\` ADD \`patient_id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`patients\` ADD PRIMARY KEY (\`patient_id\`)`);
        await queryRunner.query(`ALTER TABLE \`patients\` CHANGE \`patient_id\` \`patient_id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`patients\` ADD \`email\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD \`staff_id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD PRIMARY KEY (\`staff_id\`)`);
        await queryRunner.query(`ALTER TABLE \`staff\` CHANGE \`staff_id\` \`staff_id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD \`role\` enum ('Admin', 'Staff', 'Receptionist', 'Dentist', 'Patient', 'Guest') NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD \`email\` varchar(255) NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_c07863a38c0ca837decb81b28a\` ON \`users\` (\`patientPatientId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_64e2031265399f5690b0beba6a\` ON \`patients\` (\`email\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_902985a964245652d5e3a0f5f6\` ON \`staff\` (\`email\`)`);
        await queryRunner.query(`ALTER TABLE \`billing\` ADD CONSTRAINT \`FK_f22ac204d60b28abdbe5d846570\` FOREIGN KEY (\`appointmentAppointmentId\`) REFERENCES \`appointments\`(\`appointment_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`billing\` ADD CONSTRAINT \`FK_7a4cbee232167f589034579058d\` FOREIGN KEY (\`patientPatientId\`) REFERENCES \`patients\`(\`patient_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`patient_treatments\` ADD CONSTRAINT \`FK_9b7ee5bc21373d8458d61d5b854\` FOREIGN KEY (\`treatmentTreatmentId\`) REFERENCES \`treatments\`(\`treatment_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`patient_treatments\` ADD CONSTRAINT \`FK_81ab01dc3f9a00a10eb08b4d091\` FOREIGN KEY (\`patientPatientId\`) REFERENCES \`patients\`(\`patient_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`patient_treatments\` ADD CONSTRAINT \`FK_2593abd5b1546954e5fd64de544\` FOREIGN KEY (\`appointmentAppointmentId\`) REFERENCES \`appointments\`(\`appointment_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`appointments\` ADD CONSTRAINT \`FK_a653f25083f24810a2988e9d125\` FOREIGN KEY (\`staffStaffId\`) REFERENCES \`staff\`(\`staff_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`appointments\` ADD CONSTRAINT \`FK_669db51cd07b8a65bee9aaf9c4a\` FOREIGN KEY (\`patientPatientId\`) REFERENCES \`patients\`(\`patient_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_c07863a38c0ca837decb81b28ac\` FOREIGN KEY (\`patientPatientId\`) REFERENCES \`patients\`(\`patient_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_8ff6d2f32e511dfb73c832c961b\` FOREIGN KEY (\`staffStaffId\`) REFERENCES \`staff\`(\`staff_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
